### ISSUE TITLE
iOS requestPermission not opening the native dialog if previously it was denied

### ISSUE THREAD

**Issue by tudordumitriu** [chemerisuk/cordova-plugin-firebase-messaging#178]
Hi
I'm not sure though if this is a bug or not but I think if requestPermission is called later on (when the user decides to allow the app to send push notifications) the native dialog should be displayed.
At the moment if the user disallows push notifications the only option is to tell him to go in settings and enable the permissions.

**Comment by rohitwtbs** [comment]
This is not a bug, It is an expected behaviour of iOS.

**Comment by rohitwtbs** [comment]
Hey @chemerisuk 
 I am running into a small problem in my Cordova app. 
I have two type of firebase client side keys one for prod and one for dev.
The problem is if i have app installed with let's say dev client side keys and then i update the app with the new keys, it is still referring to the old keys and not getting the token based on the new keys. Any idea on how to resolve this?
