### ISSUE TITLE
iOS not getting notifications

### ISSUE THREAD

**Issue by jdileep14** [chemerisuk/cordova-plugin-firebase-messaging#47]
I am getting token in **getToken** function but I am not getting any notifications in iOS.i setup  everything. earlier when i used different plugin i got notifications but now i am not getting any notifications  this is sample code 
this.firebaseMessaging
				.requestPermission()
				.then((result) => {
					alert('result =>');
					alert(JSON.stringify(result));
					// this.storage.set('token', token);
					// this.devToken = token;
				})
				.catch((error) => {
					alert('error =>' + error);
				});

			/* getting firebase token  */
			this.firebaseMessaging
				.getToken()
				.then((token) => {
					alert(token);
				
				})
				.catch((error) => {
					alert(error);
				});

			this.firebaseMessaging.onMessage().subscribe(
				(data) => {
					alert(data);
					
				},
				(error) => {
					console.log('foreground message error');
				}
			);

			this.firebaseMessaging.onBackgroundMessage().subscribe(
				(data) => {
					alert(data);
					
				},
				(error) => {
					console.log('background message error');
				}
			);
		}

Thanks in advance.

**Comment by ColdDevil** [comment]
After a lot of trial&error, this worked for me:

- delete /platforms/ios folder
- delete /node_modules folder
- delete contents of /plugins
- npm install
- ionic cordova platform add ios (this should rebuild all plugins)
- ionic cordova prepare ios
- cd platforms/ios
- pod install
- open .xcworkspace in platforms/ios
- File > Workspace Settings... > Build System: Legacy Build System
- (in case this does not work automatically: select your target and configure the signing identity)
- (in case you have a version of this app on your phone: use CMD+Shift+2 and remove it from your phone!)
- build and run your app on a real device, it might not work in the simulator
- send a well-formed push-notification to Firebase e.g. via your server. **I noticed that test messages sent from the Firebase Console do not work!**

**Comment by imgx64** [comment]
I was having this issue. Turns out I had another Cordova plugin that was calling `[UNUserNotificationCenter currentNotificationCenter].delegate = self;`. After removing that plugin (fortunately, I wasn't using it), I'm receiving iOS notifications now.

So, search for `[UNUserNotificationCenter currentNotificationCenter]` in your XCode workspace and see if any other plugins are overriding the delegate.

**Comment by CesarGalindoSalgado** [comment]
Hello, I'm having the same issue with my project. Everything compiles and run perfectly. I can allow the notifications using the suggested function, I can get token, but I don't receive any notifications, foreground neither background. I would like to know if for ios, using this library, we still need to create the certificate to allow notifications or to do other steps in order to get notifications, I tryed to print in console but nothing, and I tested sending msg using my own server and the console, both perfectly worked on android. I didn't have issues in android. Is there a way to know where my project is failing?. Im running cordova 9.0.0, ios 5.0.0, xcode 10.2.1, node 10.16.0. thanks in advance.
